AllCops:
  Exclude:
    - "bin/**/*"
    - "test/**/*"
    - "Rakefile"
    - "descripto.gemspec"
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
