name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    env:
      CI: true
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
        cd test/dummy && bundle install --jobs 4 --retry 3

    - name: Set up database
      run: |
        cd test/dummy
        bin/rails db:create db:migrate RAILS_ENV=test  
    
    - name: Run tests
      run: rake test
